<?php

declare(strict_types=1);

namespace Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250911005305 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE contacts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, description VARCHAR(255) NOT NULL, person_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_33401573217BBB47 ON contacts (person_id)');
        $this->addSql('CREATE TABLE persons (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, cpf VARCHAR(14) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A25CC7D33E3E11F0 ON persons (cpf)');
        $this->addSql('ALTER TABLE contacts ADD CONSTRAINT FK_33401573217BBB47 FOREIGN KEY (person_id) REFERENCES persons (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE contacts DROP CONSTRAINT FK_33401573217BBB47');
        $this->addSql('DROP TABLE contacts');
        $this->addSql('DROP TABLE persons');
    }
}
